services:
  - type: web
    name: nurse-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: APP_SECURITY_ALLOWED_ORIGINS
        sync: false
